sudo: required
dist: trusty
language: shell
# Attempt to cache TeX
cache:
  edge: true
  yarn: true
  pip: true
  directories:
   - /tmp/texlive
   - $HOME/.texlive
   - $HOME/save

before_install:
  - sudo apt-add-repository 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
  - sudo apt-get install python-software-properties
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update 
  - sudo apt-get install --allow-unauthenticated -y -qq aria2 xzdec nodejs yarn pkg-config fuse tup wget python3 python3-pip git
  - bash scripts/getPandoc.sh
  - bash scripts/firaFonts.sh
  - cp scripts/texlive.profile $HOME/texlive.profile
  - source ./scripts/TeXLive.sh
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

install:
  - sudo yarn global add shx surge node-sass imagemin-cli
  - sudo pip3 install panflute
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

script:
  - tup

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./sap/
    domain: $SURGE_DOMAIN
  - provider: pages
    local_dir: ./sap
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
